services:
  n8n:
    image: n8nio/n8n

    ports:
      - "5678:5678"

    environment:
      - N8N_BASIC_AUTH_ACTIVE=true

      - N8N_BASIC_AUTH_USER=TuUsuario

      - N8N_BASIC_AUTH_PASSWORD=TuContrase√±a

    volumes:
      - ./n8n_data:/home/node/.n8n

      #mkdir ./backup/n8n_data
      #docker cp n8n:/home/node/.n8n ./backup/n8n_data
